export const baseAchievementDefinitions = [
  {
    key: 'press-start',
    title: 'Нажми Start',
    description: 'Сделай первый шаг в новую кампанию и начни вести свой год как главный герой.',
    category: 'story',
    rarity: 'common',
    icon: '?',
    xpReward: 80,
    targetValue: 1,
    isHidden: false,
    verificationType: 'none',
  },
  {
    key: 'npc-interaction',
    title: 'Диалог с NPC',
    description: 'Проведи 10 разговоров с незнакомыми людьми и собери социальный лут.',
    category: 'social',
    rarity: 'rare',
    icon: '?',
    xpReward: 140,
    targetValue: 10,
    isHidden: false,
    verificationType: 'none',
  },
  {
    key: 'night-mode',
    title: 'Ночной режим',
    description: 'Проживи 24 часа без соцсетей и проверь, как ощущается тишина.',
    category: 'discipline',
    rarity: 'epic',
    icon: '?',
    xpReward: 240,
    targetValue: 24,
    isHidden: false,
    verificationType: 'none',
  },
  {
    key: 'chaos-theory',
    title: 'Теория хаоса',
    description: 'Отдай день случайным решениям и посмотри, куда заведет рандом.',
    category: 'chaos',
    rarity: 'rare',
    icon: '?',
    xpReward: 160,
    targetValue: 1,
    isHidden: false,
    verificationType: 'text',
  },
  {
    key: 'explorer',
    title: 'Картограф',
    description: 'Открой 10 новых мест и обнови карту своего мира.',
    category: 'exploration',
    rarity: 'rare',
    icon: '?',
    xpReward: 180,
    targetValue: 10,
    isHidden: false,
    verificationType: 'none',
  },
  {
    key: 'main-character',
    title: 'Главный персонаж',
    description: 'Открой 7 достижений и почувствуй, что камера теперь смотрит только на тебя.',
    category: 'story',
    rarity: 'epic',
    icon: '?',
    xpReward: 260,
    targetValue: 7,
    isHidden: false,
    verificationType: 'none',
  },
  {
    key: 'break-system',
    title: 'Сломать систему',
    description: 'Сделай что-то нестандартное и вырвись из привычного сценария.',
    category: 'secret',
    rarity: 'legendary',
    icon: '?',
    xpReward: 420,
    targetValue: 1,
    isHidden: true,
    verificationType: 'ai_text',
  },
  {
    key: 'god-mode',
    title: 'Режим бога',
    description: 'Открой 3 epic-достижения и выйди на новый уровень власти над сезоном.',
    category: 'secret',
    rarity: 'legendary',
    icon: '?',
    xpReward: 480,
    targetValue: 3,
    isHidden: true,
    verificationType: 'none',
  },
  {
    key: 'silent-run',
    title: 'Тихое прохождение',
    description: 'Проведи 3 часа без музыки, подкастов и фонового шума.',
    category: 'discipline',
    rarity: 'common',
    icon: '?',
    xpReward: 90,
    targetValue: 3,
    isHidden: false,
    verificationType: 'none',
  },
  {
    key: 'speedrun-morning',
    title: 'Утренний спидран',
    description: 'Собери 5 бодрых утр без лишнего скролла и потери темпа.',
    category: 'discipline',
    rarity: 'common',
    icon: '?',
    xpReward: 100,
    targetValue: 5,
    isHidden: false,
    verificationType: 'none',
  },
  {
    key: 'random-encounter',
    title: 'Случайная встреча',
    description: 'Окажись в месте или событии, куда обычно бы не пошел.',
    category: 'exploration',
    rarity: 'rare',
    icon: '?',
    xpReward: 150,
    targetValue: 3,
    isHidden: false,
    verificationType: 'text',
  },
  {
    key: 'iron-will',
    title: 'Железная воля',
    description: 'Выдержи 7 дней подряд без срыва выбранного челленджа.',
    category: 'discipline',
    rarity: 'epic',
    icon: '?',
    xpReward: 280,
    targetValue: 7,
    isHidden: false,
    verificationType: 'none',
  },
  {
    key: 'offline-raider',
    title: 'Оффлайн-рейдер',
    description: 'Проведи вечер без мессенджеров и почувствуй, как тишина дает XP.',
    category: 'discipline',
    rarity: 'rare',
    icon: '?',
    xpReward: 170,
    targetValue: 1,
    isHidden: false,
    verificationType: 'text',
  },
  {
    key: 'glitch-walker',
    title: 'Ходок по глитчам',
    description: 'Пройди ночь без сна и доживи до рассвета как багованный персонаж.',
    category: 'chaos',
    rarity: 'legendary',
    icon: '-',
    xpReward: 450,
    targetValue: 1,
    isHidden: true,
    verificationType: 'ai_text',
  },
  {
    key: 'social-boss',
    title: 'Социальный босс',
    description: 'Собери 15 уверенных взаимодействий за неделю и не потеряй темп.',
    category: 'social',
    rarity: 'epic',
    icon: '?',
    xpReward: 300,
    targetValue: 15,
    isHidden: false,
    verificationType: 'none',
  },
  {
    key: 'deep-dive',
    title: 'Глубокое погружение',
    description: 'Отдай 4 часа одному делу без переключения между вкладками жизни.',
    category: 'discipline',
    rarity: 'rare',
    icon: '?',
    xpReward: 190,
    targetValue: 4,
    isHidden: false,
    verificationType: 'none',
  },
  {
    key: 'zero-notifications',
    title: 'Ноль уведомлений',
    description: 'Отключи уведомления на сутки и почувствуй, как интерфейс становится чище.',
    category: 'discipline',
    rarity: 'epic',
    icon: '?',
    xpReward: 250,
    targetValue: 24,
    isHidden: false,
    verificationType: 'none',
  },
  {
    key: 'secret-level',
    title: 'Тайный уровень',
    description: 'Найди скрытый маршрут года и сделай неожиданное достижение вне гайдов.',
    category: 'secret',
    rarity: 'legendary',
    icon: '?',
    xpReward: 500,
    targetValue: 1,
    isHidden: true,
    verificationType: 'ai_text',
  },
  {
    key: 'daily-streak',
    title: 'Серия без пропусков',
    description: 'Собери 14 дней подряд с отмеченным прогрессом хотя бы по одной ачивке.',
    category: 'discipline',
    rarity: 'rare',
    icon: '?',
    xpReward: 210,
    targetValue: 14,
    isHidden: false,
    verificationType: 'none',
  },
  {
    key: 'final-form',
    title: 'Финальная форма',
    description: 'Открой половину коллекции и войди в настоящий эндгейм.',
    category: 'story',
    rarity: 'legendary',
    icon: '?',
    xpReward: 520,
    targetValue: 10,
    isHidden: false,
    verificationType: 'none',
  },
];

